services:
  backend:
    image: ghcr.io/olyaprykhodko/abetka-backend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "0.0.0.0:${BACKEND_PORT:-3500}:3500"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: ghcr.io/olyaprykhodko/abetka-frontend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "0.0.0.0:${FRONTEND_PORT:-3000}:3000"

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432/tcp"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test:
        ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 120s
      timeout: 5s
      retries: 2
      start_period: 30s

  minio:
    image: bitnami/minio:2024-debian-12
    ports:
      - "0.0.0.0:${MINIO_API_PORT:-9000}:9000/tcp"
      - "0.0.0.0:${MINIO_CONSOLE_PORT:-9001}:9001/tcp"
    env_file:
      - .env.minio
    volumes:
      - "minio-data:/bitnami/minio/data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 120s
      timeout: 5s
      retries: 2
      start_period: 30s

volumes:
  postgres-data:
  minio-data:
