name: Dependabot Reviewer
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: write
  actions: write

jobs:
  review-dependabot-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2
        with:
          alert-lookup: true
          compat-lookup: true
          github-token: ${{ github.token }}

      - name: Label PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ github.token }}
